In [0]:
import numpy as np


In [0]:
data1 = [1, 2, 3, 4, 5]    # the list named data1 is creayed
print(data1)

array1 = np.array(data1)   # the list named data1 is converted into array
print(array1)

data2 = [range(1, 5), range(5, 9)] 
print(data2)

array2 = np.array(data2)    # by using the range command the array2 is created which have 2 rows and 4 colomns
print(array2)

array2.tolist()    # the array2 is converted into list

[1, 2, 3, 4, 5]
[1 2 3 4 5]
[range(1, 5), range(5, 9)]
[[1 2 3 4]
 [5 6 7 8]]


[[1, 2, 3, 4], [5, 6, 7, 8]]

In [0]:
a = np.zeros(10)  # 1 dimensional array is created having 10 zeros
print(a)

a = np.zeros((3, 6))  # 3 rows and 6 coloms array having zeros is created
print(a)

a = np.ones(10)    # 1 dimensional array is created having 10 ones
print(a)

a = np.linspace(0, 1, 5) # start, stop, and no. of items between
print(a)

a = np.logspace(0, 3, 4) # giving the value as the result of 3 power of 10 in positive and negative term
print(a)

#logspace return numbers spaced evenly on a log scale

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0.   0.25 0.5  0.75 1.  ]
[   1.   10.  100. 1000.]


In [0]:
int_array = np.arange(5)  # an array of 5 index is created
print(int_array)

float_array = int_array.astype(float) # the array is converted into the float type
print(float_array)

[0 1 2 3 4]
[0. 1. 2. 3. 4.]


In [0]:
print(array1.dtype) # determine the type of data and total number of bytes taken in array 
print(array2.dtype) # determine the type of data and total number of bytes taken in array 
print(array2.ndim)  # print the no. of dimension  
print(array2.shape) # print the no. of rows and no. of colomns
print(array2.size)  # print the number of items in array
print(len(array2))  # print the number of rows 

int64
int64
2
(2, 4)
8
2


In [0]:
#RESHAPE
arr = np.arange(10, dtype = float)
print(arr)
arr = np.arange(10, dtype = float).reshape((2, 5)) 

print(arr.shape) 
print(arr.reshape(5, 2)) # 10 index number starting from 0 till 9 is given in 5 rows and 2 colomns

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
(2, 5)
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]


In [0]:
#add an axis
a = np.array([0, 1]) # 1 dimensional array
print(a)

#a_col = a[: , np.newaxis] # the 1 dimensional array is converted into 2 dimension 2 rows and 1 colomn
#print(a_col)

a_col = a [:, None]  # the 1 dimensional array is converted into 2 dimension 2 rows and 1 colomn
print(a_col)

[0 1]
[[0]
 [1]]


In [0]:
#transpose
print(a_col.T) # the transpose of matrix is taken

[[0 1]]


In [0]:
#flatten
import numpy as np
x = [[2, 3, 4], [0, 5, 7], [1, 9, 8]]
x_1 = np.array(x)
print(x_1)
b = x_1.flatten()
print(b)


[[2 3 4]
 [0 5 7]
 [1 9 8]]
[2 3 4 0 5 7 1 9 8]


In [0]:
#ravel 
arr_flt = arr.ravel()
print(arr_flt)

arr_flt[0] = 33 # the [0] is replaced by 33
print(arr_flt)

print(arr) # print a 2 dimensional array

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[33.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
[[33.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]


In [0]:
#STACK ARRAY
x = np.array([0, 1]) # matrix x
print(x)

y = np.array([2, 3])  # matrix y
print(y) 

xy = np.stack((x, y)) # stack is used to merge the matrix x and y.
print(xy)

xy = np.stack((x, y)).T  #T is used for the transpose of the matrix 
print(xy)

np.hstack((x[: , None], y[:, None])) #used for the transpose of the matrix

[0 1]
[2 3]
[[0 1]
 [2 3]]
[[0 2]
 [1 3]]


array([[0, 2],
       [1, 3]])

In [0]:
#selection
arry = np.arange(10, dtype = float).reshape((2, 5)) #matrix of 2 rows 5 colomns having float data type and 10 index 
                                                     #number is created
print(arry)

print(arry[0]) # the first row is printed which has a index of 0
print(arry[0, 3]) # the third item from the 0 index row 
print(arry[0][3]) # the third item from the 0 index row

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
[0. 1. 2. 3. 4.]
3.0
3.0


In [0]:
#SLICING 
arry = np.arange(10, dtype = float).reshape((2, 5)) #matrix of 2 rows 5 colomns having float data type and 10 index 
                                                     #number is created
print(arry)

print(arry[0, :])    # the 0 index row with all elements till last

print(arry[:, 0])    # the 0 index colomn

print(arry[:, :2])     #colomns befor index 2 

print(arry[:, 2:])     #colomns between 2 (included) and last

arry2 = arry[:, 1:4]  #colomns between 1 (included) and 4 (excluded)
print(arry2)

arry2[0, 0] = 33    # 0 index of 0 row is replaced by 33
print(arry2)

print(arry[0, ::-1]) # the zero index row is printed in reverse order 

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
[0. 1. 2. 3. 4.]
[0. 5.]
[[0. 1.]
 [5. 6.]]
[[2. 3. 4.]
 [7. 8. 9.]]
[[1. 2. 3.]
 [6. 7. 8.]]
[[33.  2.  3.]
 [ 6.  7.  8.]]
[ 4.  3.  2. 33.  0.]


In [0]:
#FANCY INDEXING: INTEGER OR BOOLEAN ARRAY INDEXING

arry_1 = np.arange(10, dtype = float).reshape((2, 5)) #matrix of 2 rows 5 colomns having float data type and 10 index 
                                                     #number is created

print(arry_1)

arry_2 = arry_1[:, 1:4]  #colomns between 1 (included) and 4 (excluded)
print(arry2)

arry_2[0, 0] = 33    # 0 index of 0 row is replaced by 33
print(arry_2)

print(arry_1[0, ::-1]) # the zero index row is printed in reverse order 


arry_2 = arry_1[:, [1, 2, 3]] 
print(arry_2)

arry_2[0, 0] = 44  # 0 index of 0 row is replaced by 44
print(arry_2)

print(arry_1)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
[[33.  2.  3.]
 [ 6.  7.  8.]]
[[33.  2.  3.]
 [ 6.  7.  8.]]
[ 4.  3.  2. 33.  0.]
[[33.  2.  3.]
 [ 6.  7.  8.]]
[[44.  2.  3.]
 [ 6.  7.  8.]]
[[ 0. 33.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]


In [0]:
arry_2 = arry_1[arry_1 > 5] # all the elements greater than 5 are printed
print(arry_2)

arry_2[0] = 44    # 0 index of 0 row is replaced by 44
print(arry_2)

print(arry_1)

[33.  6.  7.  8.  9.]
[44.  6.  7.  8.  9.]
[[ 0. 33.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]


In [0]:
arry_1[arry_1 > 5 ]= 0 # all the numbers greater than 5 will be replaced by 0
print(arry_1)

[[0. 0. 2. 3. 4.]
 [5. 0. 0. 0. 0.]]


In [0]:
# boolean array indexing

name_1 = np.array(['Bob', 'Joe', 'Will', 'Bob'])
print(name_1)

print(name_1 == 'Bob')    # return the boolean condition of whether the word is present in the string

print(name_1[name_1 != 'Bob']) # print name_1 when name_1 does not contain the word Bob

print((name_1 == 'Bob') | (name_1 == 'Will')) # the or operation using the symbol as keyword does not work here

name_1[name_1 != 'Bob'] = 'Joe' # in the string the word which is not bob is replaced with joe
print(name_1)

np.unique(name_1) 

['Bob' 'Joe' 'Will' 'Bob']
[ True False False  True]
['Joe' 'Will']
[ True False  True  True]
['Bob' 'Joe' 'Joe' 'Bob']


array(['Bob', 'Joe'], dtype='<U4')

In [0]:
#VECTORIZED OPERATION
num_1 = np.arange(5)
print(num_1)

print(num_1 * 10) # the each element of the array is multiplied by 10

num_1 = np.sqrt(num_1)  # square root of the function of the array
print(num_1)

print(np.ceil(num_1)) # the ceil is used to round up the integer nearest whole number

print(np.isnan(num_1)) # since everything in array is number thus it is checking abd telling that there is no element which is not a number (NaN)

print(num_1 + np.arange(5)) # simple addition of the element of two array

print(np.maximum(num_1, np.array([-1, -2, -3, -4, 5]))) # print the greater number after comparing the array num-1 
              # and [-1, -2, -3, -4, 5]

[0 1 2 3 4]
[ 0 10 20 30 40]
[0.         1.         1.41421356 1.73205081 2.        ]
[0. 1. 2. 2. 2.]
[False False False False False]
[0.         2.         3.41421356 4.73205081 6.        ]
[0.         1.         1.41421356 1.73205081 5.        ]


In [0]:
#compare distance
vector_1 = np.random.randn(10) # generating the 10 random value for the array
print(vector_1)

vector_2 = np.random.randn(10) # creates an array of specified shape and fills it with random values as per standard normal distribution.
print(vector_2)

distance = np.sqrt(np.sum((vector_1 - vector_2) ** 2 )) # formula to determine the distance
print(distance)

[ 0.1214765   0.84702785  0.07571178 -0.50792543 -1.40073081 -0.23166291
 -0.32770262  0.32180538  0.28692469  3.05224211]
[ 1.81000161  0.23949782 -0.44059231 -0.35399539  0.1688957   0.55671847
  0.18251658  1.0370031   0.67543354  0.40407951]
3.8119919209896507


In [0]:
#math and stats
number_1 = np.random.randn(4, 2) # random array which has 4 rows and 2 colomns
print(number_1)

print(number_1.mean())            # mean of array
print(number_1.std())             # standard division of array
print(number_1.argmin())          # index of minimun element of array
print(number_1.sum())             # sum of all index of array 
print(number_1.sum(axis = 0))     # sum of all index of array in colomn index 0 and 1
print(number_1.sum(axis = 1))     # sum of all index of array in terms of individual rows

[[-1.18087404  0.59999988]
 [ 0.44139847  1.58632371]
 [-0.58931437 -0.35619691]
 [ 0.57363737  1.60485763]]
0.334978967579309
0.9318548124378184
0
2.679831740634472
[-0.75515257  3.43498431]
[-0.58087416  2.02772218 -0.94551128  2.178495  ]


In [0]:
#boolean opeartions
print((number_1 > 0).sum())
print((number_1 > 0).any())
print((number_1 > 0).all())

5
True
False


In [0]:
#random numbers 
print(np.random.seed(12234))         # set the seed ----- provides an input for the pseudo-random number generator in Python.if you change the seed, you will get a different output.
print(np.random.rand(2, 3))          # 2 * 3 matrix --------- creates an array of specified shape and fills it with random values
print(np.random.randn(10))           # random normal --------- 1 D Array filled with randnom values
print(np.random.randint(0, 2, 10))   # 10 normally picked 0 or 1 (the lowest number can be 0 the highest can be 2 and the total number can be 10)

None
[[0.00630595 0.20303476 0.76478993]
 [0.55513384 0.74358546 0.93777808]]
[-2.79962074e-01  1.31281104e+00 -9.27155784e-01 -4.01302169e-01
 -2.31085929e+00 -2.08460156e+00  4.59241643e-01  1.62191344e+00
  1.94515120e-01 -2.08631547e-03]
[0 0 0 1 1 0 1 1 1 1]


In [0]:
#BROADCASTING

a1 = np.array([[0, 0, 0],
              [10, 10,10],
              [20, 20, 20],
              [30, 30, 30]])

b1 = np.array([0, 1, 2])

print(a1 + b1)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [0]:
#ASSINGMENT
X = np.random.randn(4, 2)
print(X)
print(X.argmin(0))

X = np.array(X)
standardized_X = (X-X.mean())/X.std()
print(standardized_X)

[[-1.06254652  0.72437607]
 [ 0.89954397 -1.1673215 ]
 [ 1.0130447  -1.86335047]
 [ 1.38646439 -0.06839843]]
[0 2]
[[-0.92351843  0.65526134]
 [ 0.81002548 -1.01608909]
 [ 0.91030552 -1.63104381]
 [ 1.24022885 -0.04516986]]


In [0]:
# In page no. 7 the addition of array is show. 
#As we can see from the pictorial depiction that the arrays are not of same dimension. 
#So the addition operation can not be achieved
#To add these array you have to make them of same dimension.
#We can achieve this by extending the array in respective row and colomn to make them of same dimension.
#when the array are converted into the 3 dimensional array then we proceed further.
#the addition is done simply by adding the respective element of both arrays.